### ISSUE TITLE
backports.functools_lru_cache

### ISSUE THREAD

**Issue by ryanrussell** [tiangolo/full-stack#1]
First -- great stack. Thanks for sharing. The best swarm stack template I've come across pre-rolled.

On ubuntu 14.04 // python 2.7, I encountered this:

$ cookiecutter https://github.com/tiangolo/full-stack
Unable to load extension: No module named functools_lru_cache

This fixed it.

$ pip install backports.functools_lru_cache

Just wanted to share in case others encounter.

**Comment by tiangolo** [comment]
Cool, thanks for sharing it.
