### ISSUE TITLE
Cannot create container for service proxy: b'Mount denied:\nThe source path "\\\\var\\\\run\\\\docker.sock:/var/run/docker.sock"\nis not a valid Windows path'

### ISSUE THREAD

**Issue by michaeltoohig** [tiangolo/full-stack#12]
The proxy container has this issue. I am using Docker-for-Windows so perhaps I need to adjust something.

**Comment by michaeltoohig** [comment]
I believe issue solved by setting an extra environment variable. https://github.com/drud/ddev/pull/753

COMPOSE_CONVERT_WINDOWS_PATHS to "true"

**Comment by tiangolo** [comment]
Hmm, interesting that it wasn't working, there are some people using it in Windows already, but maybe they were using Docker Toolbox and not Docker-for-Windows?

Thanks for sharing your solution. Let's see if someone else gets the same problem and then I'll add it to the documentation.
