### ISSUE TITLE
Expected username password for pgAdmin4 on startup after first docker-compose up

### ISSUE THREAD

**Issue by AYEG** [tiangolo/full-stack#18]
Hello,
Should I expect the pgAdmin4 username and password to be based upon the given cookiecutter variables?

 i.e.
**pgadmin_default_user_password
pgadmin_default_user**

It seems to be the default(pgadmin4@pgadmin.org, admin) every time I rebuild the container with new volume. I looked into docker logs for clues if something in the configuration is not right, but the only thing I noticed was that when I manually try to change the password in the UI it fails showing a

` SMTP socketerror: [Errno 99]`

There is no error messaging when adding a new user via user management

**Comment by michaeltoohig** [comment]
I can second this but is it possible you could change the password in `.env` and then rebuild the pgadmin?

**Comment by AYEG** [comment]
Hi! After a short break I've tried your suggestion @michaeltoohig  and unfortunately it does not help. It still asks for the default login username and password. 

I removed all volumes and did a complete rebuild of the image with the new password in the .env file. 

After this build I again checked the docker logs for pgadmin and it just prints the same:
> /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
>   """)
> NOTE: Configuring authentication for SERVER mode.
> 
> pgAdmin 4 - Application Initialisation
> ======================================
> 
> 
> pgAdmin4 init process done. Ready for start up.
> 
> Starting pgAdmin 4. Please navigate to http://0.0.0.0:5050 in your browser.

**Comment by AYEG** [comment]
PR submitted

**Comment by webmobiles** [comment]
I've get his same error , i'm using 4.18 version
