### ISSUE TITLE
Compose file invalid when running `docker-compose up -d`

### ISSUE THREAD

**Issue by jgarber** [tiangolo/full-stack#3]
The README says to run `docker-compose up -d`, but the default combination of Compose files is lacking a few images:

- proxy
- swagger-ui
- pgadmin
- flower

They are found in `docker-compose.admin.yml`, but not sure if that's what's intended to be run locally.

**Comment by tiangolo** [comment]
[Docker Compose reads](https://docs.docker.com/compose/env-file/) the file [`.env`](https://github.com/tiangolo/full-stack/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.env) to see the related configuraitons and use the modified "default" set of Docker Compose files.

Do you have that file? Is there anything that could be interfering in how Docker Compose reads that file?

**Comment by tiangolo** [comment]
I'll close this issue as there were no more comments. I'll assume you solved your problem. :heavy_check_mark:
